Add verbosity and clarification to First Item tutorial page
FabricMC/fabric-docs pull request #161
Opened 2024-08-11 22:25 UTC by jwred5

2024-08-12 09:37 UTC, IMB11 requested changes

2024-08-12 09:37 UTC, IMB11 commented on develop/items/first-item.md
> +ModItems.java
If you want to label these code blocks, use h4 headings.

2024-08-12 09:37 UTC, IMB11 commented on develop/items/first-item.md
> +With that added, running your mod will now allow you to /give yourself your {mod-id}:suspicious_substance.
Wrap templates in \`\` please. Eg; `{mod-id}: suspicious_substance.`

You could alternatively have:

```
Once you've added this method, you can run your mod and use the following command to give you the suspicious substance item;

\`\`\`command
/give @s <mod-id>:suspicious_substance
\`\`\`

Make sure to replace \`<mod-id>\` with your mod's ID!

2024-08-12 09:37 UTC, IMB11 commented on develop/items/first-item.md
> +But it still won't show up when you press 'E', for that, you will need to register the item to an Item Group, described next.
Be more specific;

It wont show up within the creative inventory...

Keybinds aren't fixed, especially vanilla ones like `Open Inventory`

2024-08-12 09:37 UTC, IMB11 commented on develop/items/first-item.md
> +For example, you can create a new "Suspicious Substance" by adding this static field to your ModItems class.
```suggestion
In this example, we will create a "Suspicious Substance" item, by adding this static field to your `ModItems` class.
```

2024-12-28 00:02 UTC, IMB11 commented
Hi, @jwred5 are you still working on this?

2024-12-29 16:16 UTC, its-miroma commented
Related to #162, #230

2025-01-15 15:21 UTC, IMB11 commented
Hi! The documentation has been updated to version 1.21.4. Please rebase your PR and update your code to align with the latest version. 

Alternatively, you can create a new branch based on the latest commit from the [`FabricMC:main`](https://github.com/FabricMC/fabric-docs/tree/main) branch, copy over your changes from the old [`jwred5:patch-1`](https://github.com/jwred5/fabric-docs/tree/patch-1) branch, update it, and open a new PR - this approach is often simpler than dealing with complex git commands if you're not the best git wrangler.

Once you've completed the updates and are confident everything is ready, feel free to unmark this as a draft. Thanks again for your contribution!

2025-10-12 20:01 UTC, its-miroma commented
Hi @jwred5, thank you for your contibution!

Unfortunately, this PR has stalled for a long time, however some other PRs seem to have addressed most issues presented here:
- #348
- #357

I'll go ahead and close this one, however if you still have any other suggestions feel free to open new issues!

Thank you!

2025-10-12 20:01 UTC, closed without merging