Add my previously written codec guide
FabricMC/fabric-docs pull request #18
Opened 2024-01-06 22:51 UTC by enjarai

This PR adds the codec guide I've previously written for https://fabric.moddedmc.wiki/, with some slight updates, fixes and tweaks. As I'm not exactly sure how this wiki will be structured, I'd like to leave integrating it into navigation and the rest of the wiki to the main contributors.

If you have any questions or would like changes made, please let me know.

2024-01-06 22:53 UTC, IMB11 requested changes
Please put any code snippets into the reference mod (see contributing style guidelines). That's the only issue so far! Looking good!

2024-01-06 22:57 UTC, enjarai commented
Due to how the code snippets are structured, I'm not sure how feasible it is to integrate them into an actual mod without significant restructuring. Most of the code, while valid, is very much simplified and compacted to address more complex topics.

2024-01-06 23:04 UTC, IMB11 commented
You can manipulate the way they are displayed using the vitepress snippet component options - it doesn't necessarily mean you have to restructure your codeblocks

2024-01-13 17:48 UTC, deirn requested changes

2024-01-13 17:48 UTC, deirn commented on develop/codecs.md
> +beanTypeRegistry.register(new Identifier("example", "counting_bean"), new BeanType<>(CountingBean.CODEC));
The `BeanType` should be initialized as a static field somewhere the `Bean` implementation can access.

Also, I don't think there's a method directly in the `Registry` instance to register, only the static method.

2024-01-13 17:48 UTC, deirn commented on develop/codecs.md
> +Registry<BeanType<?>> beanTypeRegistry = new SimpleRegistry<>(new Identifier("example", "bean_types"), Lifecycle.stable());
`SimpleRegistry` constructor doesn't accept an `Identifier` but `RegistryKey` instead.

2024-01-13 17:48 UTC, deirn commented on develop/codecs.md
> +MapCodec<Boolean> secondCodec = Codec.BOOL.fieldOf("this_statement_is_false").codec();
`MapCodec#codec` returns a `Codec` instance.

```suggestion
Codec<Integer> firstCodec = Codec.INT.fieldOf("i_am_number").codec();
Codec<Boolean> secondCodec = Codec.BOOL.fieldOf("this_statement_is_false").codec();
```

2024-01-13 17:48 UTC, deirn commented on develop/codecs.md
> +the field is present, but the value is invalid, the field will always be deserialized as the default value.
Minecraft (not DFU!) provides a method that creates an optional codec that errors if it failed to deserialize. Might worth mentioning it here.

[`Codecs#createStrictOptionalFieldCodec`](https://maven.fabricmc.net/docs/yarn-1.20.4+build.3/net/minecraft/util/dynamic/Codecs.html#createStrictOptionalFieldCodec(com.mojang.serialization.Codec,java.lang.String))

2024-01-15 19:27 UTC, IMB11 commented
@enjarai You should be able to use the snippet syntax from #19 now. (See discord thread)

2024-01-21 13:04 UTC, IMB11 commented on develop/codecs.md
> +description: A comprehensive guide for understanding and using Mojang's codec system for serializing and deserializing objects.
```suggestion
description: A comprehensive guide for understanding and using Mojang's codec system for serializing and deserializing objects.
authors:
	- enjarai
```

2024-01-21 13:05 UTC, IMB11 commented on develop/codecs.md
> +description: A comprehensive guide for understanding and using Mojang's codec system for serializing and deserializing objects.
```suggestion
description: A comprehensive guide for understanding and using Mojang's codec system for serializing and deserializing objects.
authors:
  - enjarai
```

2024-01-21 13:05 UTC, IMB11 commented on develop/codecs.md
> +	- enjarai
```suggestion
  - enjarai
```

2024-01-21 13:38 UTC, enjarai commented
@deirn thanks for the suggestions, I've incorporated them into the guide.

2024-01-21 13:44 UTC, IMB11 approved these changes, later dismissed
Seems good! :+1:

2024-01-21 14:04 UTC, IMB11 approved these changes, later dismissed

2024-01-21 14:13 UTC, IMB11 approved these changes

2024-01-21 14:13 UTC, IMB11 commented
LGTM

2024-01-21 14:13 UTC, enjarai commented
If checks fail again I will cry.

2024-01-21 14:16 UTC, merged