Fix meat
FabricMC/fabric-docs pull request #187
Opened 2024-09-30 21:44 UTC by pypro485

### Pull Request Description

This PR **addresses issue** #186 by deleting the documentation for the `food` method, as it no longer exists in version **1.21.x**.

2024-10-15 07:01 UTC, its-miroma requested changes
Hello, thank you for your contribution!

Just a simple change, then I'll merge it.

Sorry for the delay (:

2024-10-15 07:01 UTC, its-miroma commented on develop/items/food.md
> +| `saturationModifier` | Sets the amount of saturation points your item will add.                                                                                                              |
Don't duplicate the line above.

```suggestion
```

2024-10-15 07:08 UTC, its-miroma approved these changes

2024-10-17 08:24 UTC, its-miroma commented
Could you review this @modmuss50?

2024-10-17 08:25 UTC, modmuss50 approved these changes

2024-10-17 08:28 UTC, merged