update ide tips and tricks
FabricMC/fabric-docs pull request #191
Opened 2024-10-12 01:21 UTC by AnAwesomGuy

added a few small things like redo keybinds and moving blocks of code.
change ctrl n to the correct keybind, alt insert.
changed all the CTRL keybinds to add a ⌘ and also added ` + ` between the keybinds.
the default keybinds for commenting out code were added.
some of the line wraps made no sense to me so i changed some of them, can revert if necessary.
i wrote this in github's text editor so there may be some weird mistakes.

2024-10-12 02:00 UTC, kevinthegreat1 commented
The mac keybinds are wrong. `Command + N` is generate, and `double shift` is search everywhere. The rest of the keybinds for mac need to be checked too.

2024-12-27 12:32 UTC, IMB11 approved these changes, later dismissed

2024-12-27 12:33 UTC, IMB11 commented
LGTM

2024-12-27 12:38 UTC, IMB11 submitted a review, later dismissed

2024-12-27 18:06 UTC, its-miroma requested changes
Lint fixes

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +Refer to the `File > Setings > Keymap` Settings or search for the functionality elsewhere if you are using a different keyboard layout.
```suggestion
Refer to the `File > Settings > Keymap` Settings or search for the functionality elsewhere if you are using a different keyboard layout.
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +You can also use the shortcuts <kbd>⌘/CTRL</kbd> + <kbd>N</kbd> to search classes and <kbd>⌘/CTRL</kbd> + <kbd>Shift</kbd> + <kbd>N</kbd> to search all _files_.
```suggestion
You can also use the shortcuts <kbd>⌘/CTRL</kbd>+<kbd>N</kbd> to search classes and <kbd>⌘/CTRL</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd> to search all _files_.
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +Another useful tool in IntelliJ is the `Recent` window. You can open it with the Shortcut <kbd>⌘/CTRL</kbd> + <kbd>E</kbd>.
```suggestion
Another useful tool in IntelliJ is the `Recent` window. You can open it with the Shortcut <kbd>⌘/CTRL</kbd>+<kbd>E</kbd>.
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +If you need to check out either the definition or the usage of variables, methods, classes, and other things, you can press <kbd>⌘/CTRL</kbd> + <kbd>Left Click / B</kbd>
```suggestion
If you need to check out either the definition or the usage of variables, methods, classes, and other things, you can press <kbd>⌘/CTRL</kbd>+<kbd>Left Click / B</kbd>
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +You can also use <kbd>⌘/CTRL</kbd> + <kbd>⌥/Shift</kbd> + <kbd>Left Click / B</kbd>
```suggestion
You can also use <kbd>⌘/CTRL</kbd>+<kbd>⌥/Shift</kbd>+<kbd>Left Click / B</kbd>
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +### Bookmarks{#bookmarks}
```suggestion
### Bookmarks {#bookmarks}
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +By opening the `Structure` window (<kbd>⌘/Alt</kbd> + <kbd>7</kbd>) you will get an overview of your currently active class. You can see which Classes and Enums
```suggestion
By opening the `Structure` window (<kbd>⌘/Alt</kbd>+<kbd>7</kbd>) you will get an overview of your currently active class. You can see which Classes and Enums
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +By placing the cursor on a class name and pressing <kbd>⌘/CTRL</kbd> + <kbd>H</kbd> you can open a new Type Hierarchy window, which shows all parent and child classes.
```suggestion
By placing the cursor on a class name and pressing <kbd>⌘/CTRL</kbd>+<kbd>H</kbd> you can open a new Type Hierarchy window, which shows all parent and child classes.
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +If you closed it by accident or just moved your cursor to a new place, you can use <kbd>⌘/CTRL</kbd> + <kbd>Space</kbd> to open them up again.
```suggestion
If you closed it by accident or just moved your cursor to a new place, you can use <kbd>⌘/CTRL</kbd>+<kbd>Space</kbd> to open them up again.
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +The Generate menu can be quickly accessed with <kbd>Alt</kbd> + <kbd>Insert</kbd> (<kbd>⌘ Command</kbd> + <kbd>N</kbd> on Mac) or by going to `Code` at the top and selecting `Generate`.
```suggestion
The Generate menu can be quickly accessed with <kbd>Alt</kbd>+<kbd>Insert</kbd> (<kbd>⌘ Command</kbd>+<kbd>N</kbd> on Mac) or by going to `Code` at the top and selecting `Generate`.
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +### Code Generation{#code-generation}
```suggestion
### Code Generation {#code-generation}
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +In addition, you can quickly override methods with <kbd>⌘/CTRL</kbd> + <kbd>O</kbd> and implement methods with <kbd>⌘/CTRL</kbd> + <kbd>I</kbd>.
```suggestion
In addition, you can quickly override methods with <kbd>⌘/CTRL</kbd>+<kbd>O</kbd> and implement methods with <kbd>⌘/CTRL</kbd>+<kbd>I</kbd>.
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +If you closed them by accident or just moved your cursor to a new place, you can use <kbd>⌘/CTRL</kbd> + <kbd>P</kbd> to open them up again.
```suggestion
If you closed them by accident or just moved your cursor to a new place, you can use <kbd>⌘/CTRL</kbd>+<kbd>P</kbd> to open them up again.
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +It is especially useful to get used to the `Rename` refactoring tool's key bind, <kbd>Shift</kbd> + <kbd>F6</kbd>, since you will rename many things in the future.
```suggestion
It is especially useful to get used to the `Rename` refactoring tool's key bind, <kbd>Shift</kbd>+<kbd>F6</kbd>, since you will rename many things in the future.
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +| <kbd>⌘/CTRL</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd> | Replace in a bigger scope (can set specific file type mask) |
```suggestion
| Keybind                                         | Function                                                    |
| ----------------------------------------------- | ----------------------------------------------------------- |
| <kbd>⌘/CTRL</kbd>+<kbd>F</kbd>                  | Find in current file                                        |
| <kbd>⌘/CTRL</kbd>+<kbd>R</kbd>                  | Replace in current file                                     |
| <kbd>⌘/CTRL</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> | Find in a bigger scope (can set specific file type mask)    |
| <kbd>⌘/CTRL</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> | Replace in a bigger scope (can set specific file type mask) |
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +### Other Useful Keybinds{#other-keybinds}
```suggestion
### Other Useful Keybinds {#other-keybinds}
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +Selecting some text and using <kbd>⌘/CTRL</kbd> + <kbd>Shift</kbd> + <kbd>↑ Up / ↓ Down</kbd> can move the selected text up or down.
```suggestion
Selecting some text and using <kbd>⌘/CTRL</kbd>+<kbd>Shift</kbd>+<kbd>↑ Up / ↓ Down</kbd> can move the selected text up or down.
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +Instead, it may be <kbd>⌘/CTRL</kbd> + <kbd>Shift</kbd> + <kbd>Z</kbd>. You can change this in the **Keymap**.
```suggestion
In IntelliJ, the keybind for `Redo` may not be the usual <kbd>⌘/CTRL</kbd>+<kbd>Y</kbd> (Delete Line).
Instead, it may be <kbd>⌘/CTRL</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd>. You can change this in the **Keymap**.
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +## Comments{#comments}
```suggestion
## Comments {#comments}
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +To comment out code faster, you can select some text and use the <kbd>⌘/CTRL</kbd> + <kbd>/</kbd> (line comment) and <kbd>⌘/CTRL</kbd> + <kbd>⌥/Shift</kbd> + <kbd>/</kbd> (block comment) keybinds.
```suggestion
To comment out code faster, you can select some text and use the <kbd>⌘/CTRL</kbd>+<kbd>/</kbd> (line comment) and <kbd>⌘/CTRL</kbd>+<kbd>⌥/Shift</kbd>+<kbd>/</kbd> (block comment) keybinds.
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
>  <VideoPlayer src="https://youtu.be/wvo9aXbzvy4?si=oSI1NVuOKtYI1wev" title="IntelliJ IDEA Pro Tips: Postfix Completion on YouTube"/>
```suggestion
<VideoPlayer src="https://youtu.be/wvo9aXbzvy4" title="IntelliJ IDEA Pro Tips: Postfix Completion on YouTube"/>
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
>  <VideoPlayer src="https://youtu.be/wvo9aXbzvy4?si=oSI1NVuOKtYI1wev" title="IntelliJ IDEA Pro Tips: Postfix Completion on YouTube"/>
Please do the same for the link in line 250

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
>  <VideoPlayer src="https://youtu.be/V8lss58zBPI?si=XKl5tuUN-hCG_bTG" title="IntelliJ talk by Anton Arhipov on YouTube"/>
```suggestion
<VideoPlayer src="https://youtu.be/V8lss58zBPI" title="IntelliJ talk by Anton Arhipov on YouTube"/>
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +If your project uses split sources from the online [Template mod generator](https://fabricmc.net/develop/template/), there will be two sources, as indicated by the name (client/common).
```suggestion
If your project uses split sources from the online [Template mod generator](https://fabricmc.net/develop/template), there will be two sources, as indicated by the name (client/common).
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +For even more keyboard shortcuts, you can see [IntelliJ's documentation](https://www.jetbrains.com/help/idea/mastering-keyboard-shortcuts.html).
```suggestion
For even more keyboard shortcuts, you can see [IntelliJ's documentation](https://www.jetbrains.com/help/idea/mastering-keyboard-shortcuts).
```

2024-12-27 18:06 UTC, its-miroma commented on develop/ide-tips-and-tricks.md
> +For even more information, check out [Jetbrains' Tips & Tricks site](https://blog.jetbrains.com/idea/category/tips-tricks/).
```suggestion
For even more information, check out [Jetbrains' Tips & Tricks site](https://blog.jetbrains.com/idea/category/tips-tricks).
```

2024-12-27 19:22 UTC, its-miroma approved these changes

2024-12-27 20:45 UTC, IMB11 approved these changes

2024-12-27 20:45 UTC, merged