1.21.4 port
FabricMC/fabric-docs pull request #242
Opened 2024-12-30 18:08 UTC by modmuss50

2025-01-09 17:23 UTC, IMB11 commented
TODO: Before merging, make sure to merge the crowdin PR from main branch and copy it into versioned/1.21/translations ... folder

2025-01-11 03:40 UTC, keetsta approved these changes

2025-01-15 14:18 UTC, IMB11 submitted a review, later dismissed

2025-01-15 14:20 UTC, its-miroma requested changes
we must fix links in `versions/1.21/translated`

2025-01-15 14:48 UTC, IMB11 commented
LGTM

2025-01-15 14:48 UTC, IMB11 approved these changes

2025-01-15 14:50 UTC, its-miroma approved these changes

2025-01-15 14:54 UTC, merged