New Crowdin updates
FabricMC/fabric-docs pull request #244
Opened 2024-12-30 19:25 UTC by FabricMCBot

2025-01-11 16:46 UTC, its-miroma approved these changes, later dismissed

2025-01-14 21:38 UTC, its-miroma approved these changes

2025-01-14 21:40 UTC, its-miroma requested changes, later dismissed

2025-01-14 21:40 UTC, its-miroma commented on translated/ja_jp/index.md
> +    link: /players/
oops

2025-01-15 11:53 UTC, IMB11 approved these changes

2025-01-15 11:54 UTC, merged