Block Inventory article
FabricMC/fabric-docs pull request #246
Opened 2024-12-30 20:50 UTC by natri0

Added an article about implementing `Inventory` in block entities. Some stuff (e.g. `ImplementedInventory`) copied over from [wiki's "tutorial:inventory"](https://wiki.fabricmc.net/tutorial:inventory).

Tutorial covers using the `ImplementedInventory` & implementing `SidedInventory`, as well as some basic user interaction (inserting items on right-click).

2024-12-30 20:56 UTC, its-miroma commented
Thank you for your contribution!

We are temporarily not accepting PRs until we finish the update process. Follow #242 for more information.

You may keep this PR open.

2025-01-15 15:20 UTC, IMB11 commented
Hi! The documentation has been updated to version 1.21.4. Please rebase your PR and update your code to align with the latest version. 

Alternatively, you can create a new branch based on the latest commit from the [`FabricMC:main`](https://github.com/FabricMC/fabric-docs/tree/main) branch, copy over your changes from the old [`natri0:inventory`](https://github.com/natri0/fabric-docs/tree/inventory) branch, update it, and open a new PR - this approach is often simpler than dealing with complex git commands if you're not the best git wrangler.

Once you've completed the updates and are confident everything is ready, feel free to unmark this as a draft. Thanks again for your contribution!

2025-01-16 08:59 UTC, natri0 commented
updated for 1.21.4 :)

2025-01-16 09:20 UTC, its-miroma requested changes

2025-01-16 09:20 UTC, its-miroma commented on develop/blocks/inventory.md
> +## Sided Inventories
```suggestion
## Sided Inventories {#sided-inventories}
```

2025-01-16 09:20 UTC, its-miroma commented on develop/blocks/inventory.md
> +![Duplicator block & /data get block output showing the item in the inventory](/assets/develop/blocks/inventory_1.png)
```suggestion
![Duplicator block and output of `/data get block` showing the item in the inventory](/assets/develop/blocks/inventory_1.png)
```

2025-01-16 09:20 UTC, its-miroma commented on develop/blocks/inventory.md
> +Now, when you right-click the block with an item, you'll no longer have an item! If you run `/data get block` on the block, you'll see the item in the `Items` field in the NBT.
```suggestion
Now, when you right-click the block with an item, you'll no longer have it! If you run `/data get block` on the block, you'll see the item in the `Items` field in the NBT.
```

2025-01-16 09:36 UTC, JR1811 reviewed
This looks pretty good so far!

I think it would be interesting to also expand this page to explain how storing things like ItemStacks, Fluids, Energy, and so on, could be stored and retrieved. Also on that note, an example on how to use the Fabric Transfer API might be useful for that too. Or this could get its extra page, if necessary.

2025-01-16 09:36 UTC, JR1811 commented on develop/blocks/inventory.md
> +The `DuplicatorBlock` should now have a `getTicker` method that returns a reference to `DuplicatorBlockEntity::tick`.
Do we really need a ticking functionality here?
From what I can see, it's just copying the slot and is returning it asap. 

So this could be handled in the block interaction method in the custom block class, right?

Or do something like duplicating the slot every 10 ticks and then storing it in the inventory, until it's being retrieved or the stack has hit its max size.

2025-01-16 09:36 UTC, JR1811 commented on develop/blocks/inventory.md
> +In Minecraft, all blocks that can store items have an `Inventory`. This includes blocks like chests, furnaces, and hoppers.
Might be just me, but this kind of makes it sound like the `Inventory` interface is always needed to store any kind of ItemStack. Maybe mention it as "best practice" or something?

2025-02-15 17:57 UTC, its-miroma commented
Hello @natri0, are you still working on this?

2025-05-09 09:48 UTC, natri0 commented
@its-miroma sorry for the delay, was busy; i'll get back to it next week :)

2025-05-14 15:31 UTC, natri0 commented on develop/blocks/inventory.md
> +The `DuplicatorBlock` should now have a `getTicker` method that returns a reference to `DuplicatorBlockEntity::tick`.
@JR1811 changed it to only output one item every second.

2025-05-14 15:35 UTC, natri0 commented
rebased to latest main and applied changes requested by @its-miroma.

> Also on that note, an example on how to use the Fabric Transfer API might be useful for that too. Or this could get its extra page, if necessary.

@JR1811 i think a separate page (maybe "under" this one like Block Entities -> Block Entity Renderers) and a note about the existence of Fabric Transfer API would be better? don't want it to get too long/complex with marginally related parts all in the same article.

2025-05-14 16:43 UTC, its-miroma requested changes
lint fixes

2025-05-14 16:43 UTC, its-miroma commented on develop/blocks/inventory.md
> +title: Inventories
```suggestion
title: Block Inventories
```

2025-05-14 16:43 UTC, its-miroma commented on develop/blocks/inventory.md
> +# Block Inventories {#inventories}
```suggestion
---
```

2025-05-14 16:43 UTC, its-miroma commented on develop/blocks/inventory.md
> +
```suggestion
```

2025-05-14 16:43 UTC, its-miroma commented on reference/latest/src/main/java/com/example/docs/block/entity/ModBlockEntities.java
> +import com.example.docs.block.entity.custom.DuplicatorBlockEntity;
```suggestion
```

2025-05-14 16:43 UTC, its-miroma commented on develop/blocks/inventory.md
> +<VideoPlayer src="/assets/develop/blocks/inventory_2.mp4" />
```suggestion
<VideoPlayer src="/assets/develop/blocks/inventory_2.mp4">Duplicator block duplicating an oak log</VideoPlayer>
```

2025-05-14 16:43 UTC, its-miroma commented on develop/blocks/inventory.md
> +<VideoPlayer src="/assets/develop/blocks/inventory_3.webm" />
```suggestion
<VideoPlayer src="/assets/develop/blocks/inventory_3.webm">The Duplicator only activating when interacting with its top side</VideoPlayer>
```

2025-05-14 16:43 UTC, its-miroma commented on public/assets/develop/blocks/inventory_2.mp4
I don't know if it's on the guidelines, but we're only using `webm`

2025-05-22 16:44 UTC, JR1811 requested changes
Small changes, nothing major 👍🏻

2025-05-22 16:44 UTC, JR1811 commented on .vitepress/sidebars/develop.ts
> +        link: "/develop/blocks/inventory",
I would put Block Inventories under `Block Entities`.
Technically, a block(pos) inventory could be stored without a Block Entity using Persistent State.

So specifically ordering it to be categorized under `Block Entity` instead of `Block` might be clearing up that issue.

2025-05-22 16:44 UTC, JR1811 commented on sidebar_translations.json
> +  "develop.blocks.inventory": "Block Inventories",
Change the address to reflect the entry being listed in `Blocks > Block Entity` instead of `Blocks`

(For more information, see requested changes in develop.ts file).

2025-05-22 16:44 UTC, JR1811 commented on reference/latest/src/main/java/com/example/docs/block/entity/custom/DuplicatorBlockEntity.java
> +	// :::3
Reference comments are displayed in the code view?

![grafik](https://github.com/user-attachments/assets/02e716b1-4408-4fc3-bd34-c2f6f21d8c7c)

2025-09-23 17:37 UTC, its-miroma commented
Hi @natri0, sorry for the long wait, do you think you could address the last few reviews, and check if anything changed in 1.21.10, so we can get this merged? Thank you!

2025-12-13 01:18 UTC, Tenneb22 requested changes

2025-12-13 01:18 UTC, Tenneb22 commented on develop/blocks/inventory.md
> +The `getInvAvailableSlots` returns an array of the slot _indices_ that can be interacted with from the given side. In this case, we only have a single slot (`0`), so we return an array with just that
```suggestion
The `getSlotsForFace` returns an array of the slot _indices_ that can be interacted with from the given side. In this case, we only have a single slot (`0`), so we return an array with just that index.
```

2025-12-13 01:18 UTC, Tenneb22 commented on develop/blocks/inventory.md
> +Also, we should modify the `onUseWithItem` method of the `DuplicatorBlock` to actually respect the new behavior:
```suggestion
Also, we should modify the `useItemOn` method of the `DuplicatorBlock` to actually respect the new behavior:
```

2025-12-13 01:18 UTC, Tenneb22 commented on reference/latest/src/main/java/com/example/docs/block/entity/custom/DuplicatorBlockEntity.java
> +	}
```suggestion
	public static void tick(Level world, BlockPos blockPos, BlockState blockState, DuplicatorBlockEntity duplicatorBlockEntity) {
		if (duplicatorBlockEntity.isEmpty()) return;
		duplicatorBlockEntity.timeSinceDropped++;

		if (duplicatorBlockEntity.timeSinceDropped < 10) return;
		duplicatorBlockEntity.timeSinceDropped = 0;

		ItemStack duplicate = duplicatorBlockEntity.getItem(0).split(1);

		Block.popResourceFromFace(world, blockPos, Direction.UP, duplicate);
		Block.popResourceFromFace(world, blockPos, Direction.UP, duplicate);
	}
```
Maybe use an early return for a cleaner code style?

2026-02-28 08:19 UTC, Tenneb22 commented on develop/blocks/inventory.md
> +Then, we need to create a `DuplicatorBlockEntity`, which needs to implement the `Container` interface. Thankfully, there's a helper called `ImplementedInventory` that does most of the work, leaving u
>  Thankfully, there's a helper called `ImplementedInventory` that does most of the work, leaving us with just a few methods to implement.

The tutorial mentions `ImplementedInventory`, but the code is never shown. I'd say that this could mislead someone into thinking it is a helper from Minecraft itself or fapi, which is not the case.

Is it feasible to embed the code for ImplementInventory, but make it collapsible, so it doesn't take up too much space on the page? ( something like `<details>`, but that doesn't work directly with a code reference )

2026-02-28 10:01 UTC, its-miroma commented on develop/blocks/inventory.md
> +Then, we need to create a `DuplicatorBlockEntity`, which needs to implement the `Container` interface. Thankfully, there's a helper called `ImplementedInventory` that does most of the work, leaving u
Yes, one can do:

```md
::: details Show `ImplementedInventory`

@[code transcludeWith=:::whatever](@/reference/.../ImplementedInventory.java)

:::
```

though as you said the sentence implies it comes from Minecraft or API, which must be clarified

2026-03-01 00:46 UTC, its-miroma requested changes
I think this article is very close to being merged. why was it still a draft?

2026-03-01 00:46 UTC, its-miroma commented on .vitepress/sidebars/develop.ts
> +            text: "develop.blocks.inventory",
As was pointed out by someone else, this should be under Block Entities? 
Also, the file name can be `containers`.

2026-03-01 00:46 UTC, its-miroma commented on develop/blocks/inventory.md
> +description: Learn how to add containers to your blocks.
```suggestion
description: Learn how to add containers to your block entities.
```

2026-03-01 00:46 UTC, its-miroma commented on develop/blocks/inventory.md
> +In Minecraft, a best practice when creating blocks that can store items is to implement `Container`. It is implemented by blocks like chests and furnaces. This makes it possible to, for example, inte
```suggestion
It's good practice when creating blocks that can store items, like chests and furnaces, is to implement `Container`. This makes it possible to, for example, interact with the block using hoppers.
```

2026-03-01 00:46 UTC, its-miroma commented on develop/blocks/inventory.md
> +Actually, on second thought, shouldn't a _duplicator_ block duplicate items? Let's make it so that the block duplicates the stack you threw in it, but only two items at a time. And let's make it wait
```suggestion
Let's now make it so that the block duplicates the stack you threw in it, but only two items at a time. And let's make it wait a second every time to not spam the player with items!
```

2026-03-01 00:46 UTC, its-miroma commented on reference/latest/src/main/java/com/example/docs/container/ImplementedContainer.java
> +	 * Retrieves the item list of this inventory.
All comments in this file need to be updated to mojmap.

2026-03-03 21:31 UTC, Tenneb22 commented on develop/blocks/block-containers.md
> +This should be familiar to the reader if they've followed the [Creating Your First Block](../blocks/first-block) and [Block Entities](../blocks/block-entities) guides. We'll create a `DuplicatorBlock
Maybe I'm a bit picky about this, but when saying " [...] that extends `BaseEntityBlock` and implements `EntityBlock`", I'm under the impression that I need to create a class like following:
```java
public class DuplicatorBlock extends BaseEntityBlock implements EntityBlock
```
But that assumption is wrong as I look into the code. Nothing heavy, but just confusing at first.

2026-03-04 22:24 UTC, its-miroma approved these changes, later dismissed

2026-03-04 22:24 UTC, its-miroma commented on develop/blocks/block-containers.md
> +It's good practice when creating blocks that can store items, like chests and furnaces, is to implement `Container`. This makes it possible to, for example, interact with the block using hoppers.
```suggestion
It's good practice when creating blocks that can store items, like chests and furnaces, to implement `Container`. This makes it possible to, for example, interact with the block using hoppers.
```

2026-03-04 22:34 UTC, Tenneb22 approved these changes

2026-03-05 05:18 UTC, its-miroma approved these changes

2026-03-05 05:23 UTC, cassiancc approved these changes

2026-03-05 15:48 UTC, merged