Update to 1.21.4: "Rendering"
FabricMC/fabric-docs pull request #248
Opened 2024-12-30 21:17 UTC by IMB11

This PR verifies and updates the pages in the "Rendering" category.

2024-12-30 21:36 UTC, its-miroma commented on develop/rendering/hud.md
> +### Tick Delta {#tickdelta}
```suggestion
### Tick Delta {#tick-delta}
```

2024-12-30 21:36 UTC, its-miroma commented
cc. @Octol1ttle

2024-12-31 06:05 UTC, Octol1ttle requested changes

2024-12-31 06:05 UTC, Octol1ttle commented on develop/rendering/hud.md
> +To register to this event, you can simply call `HudRenderCallback.EVENT.register` and pass in a lambda that takes a `DrawContext` and a `float` (tickDelta) as parameters.
In 1.21.4, `HudRenderCallback` provides a `RenderTickCounter` instead of a `float`

2024-12-31 06:05 UTC, Octol1ttle commented on develop/rendering/hud.md
> +| 10    | `1.0 (9÷9)` (new tick)                       |
This section was confusing to me when I first read it. The first sentence assumes that the game is running at 60 FPS, but the table uses 200 FPS

2024-12-31 06:05 UTC, Octol1ttle commented on develop/rendering/hud.md
> +Practically, let's say you want to lerp a color over time. You can use the `tickDeltaManager` to get the tickDelta, and store it over time to lerp the color:
Is this a Mojmap name? It's called `RenderTickCounter` in Yarn

2024-12-31 06:05 UTC, Octol1ttle commented on develop/rendering/hud.md
https://github.com/FabricMC/fabric-docs/blob/port/1.21.4/reference/latest/src/client/java/com/example/docs/rendering/HudRenderingEntrypoint.java

`totalTickDelta` is still a flawed way to lerp a color like this. It will *appear* to work fine at low FPS, but at higher FPS (120+) it will look very broken (for reasons I shouldn't have to explain here)

The best way for that example to work is to use `Util.getMeasuringTimeMs()` to make a `timeDelta` and have a `totalTimeDelta`.

If we want to show the importance of `tickDelta`, we need something that is tick-based. A good example would be rendering text above the entity (similar to how it's done in the Block Entity Renderers article). Without using `tickDelta`, the text will jitter.

2024-12-31 10:56 UTC, IMB11 commented on develop/rendering/hud.md
> +Practically, let's say you want to lerp a color over time. You can use the `tickDeltaManager` to get the tickDelta, and store it over time to lerp the color:
It's the name of the parameter passed by the event

2024-12-31 10:57 UTC, IMB11 commented on develop/rendering/hud.md
> +| 10    | `1.0 (9÷9)` (new tick)                       |
Ah, I forgot to update the FPS

2024-12-31 13:13 UTC, Octol1ttle approved these changes
Looks fine to me.

2024-12-31 13:57 UTC, its-miroma approved these changes
The linter will run once this is merged into #242

2025-01-08 14:25 UTC, merged