Commands Guide #1
FabricMC/fabric-docs pull request #26
Opened 2024-01-24 14:42 UTC by dicedpixels

Ports the main "Commands" page from the Wiki. There 5 more pages supplementing this one. I will port them later.

There are no major changes other than removing any reference to static imports (which seemed to confuse people a lot). Client commands are in their own section.

I also excluded the large block of method calls under "What can the `ServerCommandSource` do?" since it felt unnecessary. I'm open to adding this if there's a different opinion.

Code is directly pulled from the reference mod except the lambda in line 44.

2024-01-24 15:32 UTC, IMB11 requested changes
Looks good, but could potentially be split up into three pages:

- Introduction To Commands (What you have so far, brief touch on basic arguments)
- Dynamic Commands (mentioned in the FAQ, this could be expanded upon as there's quite a few use cases for it)
- Command Arguments (custom command argument types, how to make command arguments that work without mod on client side too - spoofing types)

2024-01-24 15:32 UTC, IMB11 commented on develop/commands/creating-commands.md
> +#### Arguments
It might be worth making this a seperate page, and going over custom arguments as well.

2024-01-24 15:32 UTC, IMB11 commented on develop/commands/creating-commands.md
> +###### Can I register commands in runtime?
Might be worth making this a new page, "Dynamic Commands"

2024-01-24 15:32 UTC, IMB11 commented on develop/commands/creating-commands.md
> +###### Can I unregister commands in runtime?
See previous comment. (Dynamic Commands)

2024-01-24 15:32 UTC, IMB11 commented on develop/commands/creating-commands.md
> +For information on registering callbacks, please see the Events guide.
```suggestion
For information on registering callbacks, please see the [Events](../events.md) guide.
```

2024-01-24 15:32 UTC, IMB11 commented on develop/commands/creating-commands.md
> +If the command fails, instead of calling `sendFeedback()`, you may directly throw a `CommandSyntaxException`.
Generally, you can throw any exception, and the server/client will handle it appropriately. `CommandSyntaxException` is usually just for syntax errors in the various arguments, nothing is stopping the developer from writing their own exception classes that the server/client can format in the chat - might be worth mentioning that too.

2024-01-24 15:32 UTC, IMB11 commented on develop/commands/creating-commands.md
> +The integer can be considered the result of the command. Typically negative values mean a command has failed and will do
I believe there's an enum that can be used for this - correct me if im wrong.

2024-01-24 15:42 UTC, IMB11 commented on develop/commands/creating-commands.md
> +The integer can be considered the result of the command. Typically negative values mean a command has failed and will do
`Command.SINGLE_SUCCESS` etc.

2024-01-24 17:38 UTC, dicedpixels commented
> Looks good, but could potentially be split up into three pages:
> 
> * Introduction To Commands (What you have so far, brief touch on basic arguments)
> * Dynamic Commands (mentioned in the FAQ, this could be expanded upon as there's quite a few use cases for it)
> * Command Arguments (custom command argument types, how to make command arguments that work without mod on client side too - spoofing types)

Sure! As a start, I will move the rest of the command related pages here. We'll reorganize and add new pages after that.

2024-02-04 18:52 UTC, IMB11 submitted a review, later dismissed

2024-02-09 22:40 UTC, modmuss50 submitted a review, later dismissed

2024-02-10 12:11 UTC, IMB11 approved these changes

2024-02-10 12:11 UTC, merged