Getting Started: Project/IDE setup.
FabricMC/fabric-docs pull request #47
Opened 2024-02-13 21:43 UTC by IMB11

Closes #29

2024-03-20 14:21 UTC, mrjasonn requested changes
I would suggest making more clear that other mappings can be used as well, not only Yarn as this part below makes it seem like there are no other options:

> Minecraft: Java Edition is obfuscated by Mojang, making modification alone difficult. However, with the help of modding tools like Fabric, modding becomes much easier - this is where Yarn comes in.
>
> Yarn remaps the obfuscated code to a human-readable format, making it easier for modders to understand and modify the game's code - it's crucial for modding to be possible.
>
> Loom allows you to easily develop and compile mods against the remapped code, and Fabric Loader allows you to load these mods into the game.

2024-03-26 01:46 UTC, mrjasonn reviewed
ok the mappings part seems good, nice

2024-04-02 20:50 UTC, Superkat32 approved these changes, later dismissed

2024-04-03 20:23 UTC, Superkat32 approved these changes

2024-04-03 20:25 UTC, merged