Start working on Block Guides
FabricMC/fabric-docs pull request #49
Opened 2024-02-16 17:20 UTC by apple502j

2024-02-18 18:43 UTC, modmuss50 reviewed
This is a great start, there are checkstyle warnings in the code that need fixing and some minor comments.

2024-02-18 18:43 UTC, modmuss50 commented on .vitepress/sidebars/develop.ts
> +    {
Nit, formatting.

2024-02-18 18:43 UTC, modmuss50 commented on develop/blocks/basics.md
> +![](/reference/latest/src/main/resources/assets/fabric-docs-reference/textures/block/border.png)
This is quite small on the web page, can the size be increased?

2024-02-18 18:43 UTC, modmuss50 commented on develop/blocks/basics.md
> +@[code lang=json](@/reference/latest/src/main/resources/assets/fabric-docs-reference/models/block/border.json)
This is good so dont change anything, but I do think we want to encorage the use of data generation, especially as its likely going to be a lot more important in future updates.

2024-02-18 18:43 UTC, modmuss50 commented on develop/blocks/basics.md
> +Let's give the border block a texture with white background and black borders, like this. Most block textures are 16-by-16 square. This is placed at `/textures/block/border.png`, inside the mod resou
Maybe mention where the resources are? eg. `src/client/resources` ?

2024-02-18 18:43 UTC, modmuss50 commented on develop/blocks/basics.md
> +![](/reference/latest/src/main/resources/assets/fabric-docs-reference/textures/block/border.png)
Assets should be in src/client not src/main

2024-02-18 18:43 UTC, modmuss50 commented on develop/blocks/basics.md
> +:::
Note: It should be possible to remove these in 1.20.5 :)

2024-02-19 19:38 UTC, IMB11 commented on develop/blocks/basics.md
> +A block, at its simplest form, has no functionality and only one "block state". A block state is a combination of properties, or variations, for the same block - things like rotations, crop age, or r
See my overall review comment, this is a prime example of a bulky paragraph, you should really split this up.

```suggestion
Blocks in their most basic form are static objects with a single appearance. To gain variations (like rotation, growth stage, or activation state), a block uses "block states". 

A block can only have a limited number of these predefined states. If a block needs more complex data storage or the ability to perform actions, it requires an associated "block entity", which offers customizable storage and the capacity to run logic each tick.
```

2024-02-19 19:39 UTC, IMB11 requested changes
It's good! But I think the main issue is that the paragraphs are too chunky and may be a bit tedious on the eyes - try split them up.

2024-03-03 15:12 UTC, IMB11 commented
ref: https://github.com/FabricMC/fabric-docs/pull/50#discussion_r1510295736

2024-03-25 19:11 UTC, IMB11 commented
I think this will be a very good introductory pull request adding some preliminary block stuff, I believe that data generation should be focused on before going into complex detail about block models, states, loot tables etc.

2024-03-25 19:12 UTC, IMB11 submitted a review, later dismissed

2024-04-04 11:51 UTC, IMB11 commented
Going to close and rewrite this.

2024-04-04 11:51 UTC, closed without merging